### ISSUE TITLE
Open question: chemical formula equivalent to mmpdb

### ISSUE THREAD

**Issue by tantrev** [rdkit/mmpdb#1]
This isn't so much a bug report, as it is an open question if there is any software like mmpdb that works strictly off chemical formulas (as opposed to chemical structures)?  I am working with mass spectrometry data and could very much use such functionality.  Thank you in advance.

**Comment by KramerChristian** [comment]
Hi Trevor,

I am not aware of any other open-source software for MMP analysis apart from this one and mmpa which is available through the RDKit Contrib. Both mmpdb and mmpa work with the same input.

Could you explain what you mean with chemical formulas as opposed to chemical structures?

Best regards,
Christian

**Comment by KramerChristian** [comment]
I will close this thread due to inactivity.
