### ISSUE TITLE
How to know the number of pairs & rules from generated .mmpdb file? 

### ISSUE THREAD

**Issue by chf42** [rdkit/mmpdb#10]
Hi all,

I would like to know if there is a function to show the number of pairs & rules from already generated .mmpdb file. Previously, once I generated the .mmpdb database, the information of the number of pairs and rules is shown on the screen. But I would like to review these information without regenerating the database. 

Appreciate if anyone else can help me figure a way out.

Thanks,
Cheng

**Comment by adalke** [comment]
Use `mmpdb list`. See `mmpdb list --help` for examples.

**Comment by chf42** [comment]
@adalke Thanks, Andrew. That works!
