### ISSUE TITLE
How to output a list of ID of compounds forming pairs?

### ISSUE THREAD

**Issue by den2882** [rdkit/mmpdb#11]
This is not clear to me. Thanks

**Comment by adalke** [comment]
Do you mean when doing a prediction, as in the "mmpdb predict" described at https://github.com/rdkit/mmpdb#5-use-mmp-to-make-a-prediction ?

If so, the last paragraph of that section is:

> You might try enabling the "--explain" option to see why the algorithm selected a given transformation, or use "--save-details" to save the list of possible rules to the file 'pred_detail_rules.txt' and to save the list of rule pairs to "pred_detail_pairs.txt".

Is that what you are looking for?

**Comment by den2882** [comment]
I am using MMPs to navigate the SAR, which is a bit different from trying to compute statistics and rules for transformations. I would like to fragment the molecules using only typical synthetic routes (aryl-alkyl cuts and amides, or simply all sp3-sp2 bond cuts). Then retrieve the list of compounds forming pairs to review them manually. 

For instance for 10 compounds with ID1,ID2,...,ID10.
It would give me the following information:
ID1 <--> ID3
ID1 <--> ID5
ID2 <--> ID4
etc...

**Comment by adalke** [comment]
An earlier version of mmpdb supported `mmpdb rulecat` to dump the rules from the database, but there wasn't a specific need or budget to update that for the public release.

What you can do instead is do `mmpb index` and specify a CSV file as the output. The `mmpdb index --help` output mentions "The 'csv' format is a tab-separated table with the columns:  SMILES1  SMILES2  id1  id2  V1>>V2  C".

**Comment by KramerChristian** [comment]
Hi den2882,

does specifying the .csv output solve the issue? If yes, I would like to close it.

Best regards,
Christian

**Comment by den2882** [comment]
It worked. Thanks!
