### ISSUE TITLE
No statistics information in the output when using transform without property argument

### ISSUE THREAD

**Issue by chf42** [rdkit/mmpdb#28]
Hi all,

I am using the MMP transform without properties information.

For example,
`python mmpdb transform test_data.mmpdb --smiles 'c1cccnc1O' --no-properties` 

Output
ID	SMILES
1	Clc1ccccn1
2	Nc1ccccn1
3	c1ccncc1

In the output, I only got ID and Smiles. But I would like to print other useful information including 'from_smiles,' 'to_smiles', 'radius', 'rule_environment_id', 'count'. Those statistics could give us some confidence for the transform. I think those statistics should be independent of properties. I am curious if there is a way to output those statistics with generated molecules if we work with a MMPDB without property information. 

Thanks, Cheng

**Comment by KramerChristian** [comment]
Hi Cheng,

there is currently no way to output the information that you listed if you call mmpdb transform with the --no-properties flag. It can be added, but that would be a code enhancement project.

A workaround that works with the current version of mmpdb is to use a dummy property that can be calculated for all compounds like e.g. molecular weight during indexing. If you then query for MWt changes, you should get the from_smiles, to_smiles, counts etc. for all results.

Bests,
Christian

**Comment by chf42** [comment]
Hi Christian,

Thank you for the kind response. The workaround should work fine. 

Best,
Cheng
