### ISSUE TITLE
How to get environment smiles?

### ISSUE THREAD

**Issue by iwatobipen** [rdkit/mmpdb#33]
Dear,
Thanks for developing the nice tool.
And I would like to know how to get environment smiles. When mmpdb is created, there is the  environment_fingerprint table which has id and env_fp. I would like to get smiles which is corresponding to each fingerprint.
Any advice or suggestions are greatly appreciated.
Thanks,

**Comment by KramerChristian** [comment]
Hi Taka,

there is currently no direct support for this. But you can use a workaround to get some environment smiles as discussed in this issue: https://github.com/rdkit/mmpdb/issues/26.

It is also one of the issues that Andrew wanted to tackle with a crowdfunded mmpdb developmetn initiative, as described here: http://mmpdb.dalkescientific.com/goals.html#goal2
Not sure whether this initiative is still alive though.

I hope this helps. Bests,
Christian

**Comment by iwatobipen** [comment]
Hi Christian,

Thanks for your prompt reply it's really helpful information. I'll try it.
Thanks again ;)
Best,
Taka

**Comment by KramerChristian** [comment]
I will close the issue. We can reopen it if any other questions related to this come up.
